### ISSUE TITLE
Navbar functionality doesn't work

### ISSUE THREAD

**Issue by HarishT-dev** [HarishT-dev/harish.github.io#2]
I am working on the responsive website which deals with the food services. It has an issue with the navbar doesn't work when checked in Mobile.
![ciaoo](https://user-images.githubusercontent.com/72560242/95666213-1a953f80-0b75-11eb-82e6-21cf11fee638.PNG)

**Comment by Niaz-Ul-Haque** [comment]
Please assign me this problem. Thank you!

**Comment by Robin-dev-Tester** [comment]
I have understood what needs to be done. Please assign to me this problem. Thanks in advance.

**Comment by HarishT-dev** [comment]
Accepted

**Comment by HarishT-dev** [comment]
Thanks a bunch :)
